//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beatmapper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Beatmapper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BeatD {
            get {
                object obj = ResourceManager.GetObject("BeatD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BeatF {
            get {
                object obj = ResourceManager.GetObject("BeatF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BeatJ {
            get {
                object obj = ResourceManager.GetObject("BeatJ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BeatK {
            get {
                object obj = ResourceManager.GetObject("BeatK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Bleed {
            get {
                return ResourceManager.GetStream("Bleed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonD {
            get {
                object obj = ResourceManager.GetObject("ButtonD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonF {
            get {
                object obj = ResourceManager.GetObject("ButtonF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonJ {
            get {
                object obj = ResourceManager.GetObject("ButtonJ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonK {
            get {
                object obj = ResourceManager.GetObject("ButtonK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 800bpm 0000 0000 0000 0000 0010 0000 0100 0000 0000 0001 0000 0000 0020 0000 0032 0000 0203 0000 2300 0000 3002 0000 1003 0001 0010 0000 0001 1000 0000 0010 1000 0000 0200 0000 0000 0000 1300 0100 0001 0010 0001 0000 0100 1000 0000 0100 0020 0000 2030 0000 3000 0100 0010 0000 0000 0000 1000 0000 0100 0000 0000 0000 0001 0000 0100 0000 1000 0001 0020 0000 0000 0000 0031 0100 1000 0100 1000 1000 0001 0100 0001 0010 1000 0000 0002 0003 1000 0100 0010 0000 1000 0001 0000 0010 0100 0000 0020 0000 0000 0000 0130  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Fabulous {
            get {
                return ResourceManager.GetString("Fabulous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Fabulous_ {
            get {
                object obj = ResourceManager.GetObject("Fabulous_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Good_ {
            get {
                object obj = ResourceManager.GetObject("Good_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 122bpm 0000 0000 0000 0000 0000 0000 0000 0101 1000 1110 0000 0001 0000 1000 0111 0000 0010 0000 0010 0000 0010 1000 0001 0101 1000 0100 0101 1000 0100 0101 1000 0100 0101 1000 0100 0101 0100 1000 1000 1111 0100 0100 0010 0100 0001 1100 1000 1100 0100 0100 0010 0100 0001 1100 1000 1100 0100 0100 0010 0100 0001 1100 1000 1100 0100 0100 0010 0100 0001 1000 0100 0001 0100 0010 1000 0010 0100 0001 0100 0010 0001 1000 0110 0010 1000 0001 0001 1000 0010 0100 0100 0010 1000 0001 0001 0100 0010 0010 0100 1000 0010  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Hard {
            get {
                return ResourceManager.GetString("Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream I_Can_t_Stop {
            get {
                return ResourceManager.GetStream("I_Can_t_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 260bpm 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 1100 0000 0011 0000 1100 0000 0011 0000 1100 0000 0011 0000 1100 0000 0011 0000 1100 0000 0011 0000 1100 0000 0011 0000 1100 0000 0000 0000 0000 0000 0000 0011 1111 1100 1111 0011 1111 1100 1111 0011 1111 1100 1111 0011 1111 1100 1111 0011 1111 1100 1111 0011 1111 1100 1111 0000 0000 0000 0000 0000 0000 1100 1000 0011 0100 1100 0010 0011 0001 1100 0001 0011 0010 1100 0100 0011 1000 1100 1000 0011 1000 1100 0100 0011 0010 1100 0001 0011 0001  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Insane {
            get {
                return ResourceManager.GetString("Insane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Miss_ {
            get {
                object obj = ResourceManager.GetObject("Miss_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream New_Divide {
            get {
                return ResourceManager.GetStream("New_Divide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap No_Effect {
            get {
                object obj = ResourceManager.GetObject("No_Effect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 140bpm 0000 0000 0000 0000 0000 0000 0001 1000 0100 1001 0120 1002 1002 0100 0120 0130 0130 0100 0001 1001 0001 1001 0010 0013 0130 0311 0010 0100 1000 0001 1000 1010 1010 0101 0101 0010 1000 0010 0001 1100 0010 0100 1111 0011 1100 0010 0101 1010 0001 0100 0010 1000 0010 0001 0100 0010 1000 0110 0110 0001 1000 0001 1000 1100 1110 0001 0110 1010 1111 1111 1011 1001 0000 1010 0111 1101 1111 0010 1000 0010 0001 0111 1101 0010 1000 0010 0001 1000 0010 0001 0100 0010 1000 1000 0001 0001 1000 0010 0001 0111 1101  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ok {
            get {
                object obj = ResourceManager.GetObject("Ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Razor_Sharp {
            get {
                return ResourceManager.GetStream("Razor_Sharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tmpButtonD {
            get {
                object obj = ResourceManager.GetObject("tmpButtonD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tmpButtonF {
            get {
                object obj = ResourceManager.GetObject("tmpButtonF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tmpButtonJ {
            get {
                object obj = ResourceManager.GetObject("tmpButtonJ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tmpButtonK {
            get {
                object obj = ResourceManager.GetObject("tmpButtonK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
